// svelte-app/src/TodoList.svelte
<script>
  import { itemStore } from "./store";

  const handleRemoveItem = item => {
    itemStore.removeItem(item);
  };
</script>

<style>
  ul {
    list-style-type: none;
  }
</style>

<ul>
  {#each $itemStore as item}
    <li>
      {item}
      <button on:click={() => handleRemoveItem(item)}>Remote Item</button>
    </li>
  {/each}
  {#if $itemStore.length === 0}
    <div>There is not any item added. Please add one</div>
  {/if}
</ul>

// react-app/src/TodoList.js
import React, { useContext } from 'react';
import { TodoListContext } from './store';

export const TodoList = () => {
    const todoListContext = useContext(TodoListContext);
    const handleRemove = (item) => {
        todoListContext.removeItem(item);
    }

    const { todoList } = todoListContext;

    return (
        <ul>
            {todoList && todoList.map(todoList => {
                return (
                    <li>
                        {todoList}
                        <button onClick={handleRemove.bind(null, todoList)}>Remote Item</button>
                    </li>
                )
            })}
            {(todoList.length === 0) && (<div>There is not any item added. Please add one</div>)}
        </ul>
    )
}
