// svelte-app/src/TodoHeader.svelte
<script>
  import { onMount } from "svelte";
  import { itemStore } from "./store";

  let value;

  onMount(() => {
    value = "";
  });

  const handleAddItem = () => {
    itemStore.addItem(value);
    value = "";
  };
</script>

<style>
  [disabled] {
    color: graytext;
  }
</style>

<input type="text" bind:value placeholder="Item name" />
<button on:click={handleAddItem} disabled={!value} class:disabled={!value}>
  Add Item
</button>

// react-app/src/TodoHeader.js
import React, { useContext, useState } from 'react';
import { TodoListContext } from './store';

export const TodoHeader = () => {
    const { addItem } = useContext(TodoListContext);

    const [itemName, setItemName] = useState('')

    const handleAddItem = (e) => {
        e.preventDefault();
        addItem(itemName);
        setItemName('');
    }

    return (
        <>
            <input placeholder="Item name" type="text" value={itemName} onChange={(event) => setItemName(event.target.value.trim())} />
            <button onClick={handleAddItem} disabled={!itemName} className={!itemName && 'disabled'}>Add Item</button>
        </>
    )
}
